name: CI

on: push

jobs:
  mix_test:
    name: '${{matrix.elixir}} x ${{matrix.otp}} (Elixir x Erlang/OTP) mix test'
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 19.3.6.13
            elixir: 1.7.4
          - otp: 20.3.8.26
            elixir: 1.8.2
          - otp: 20.3.8.26
            elixir: 1.9.4
          - otp: 21.3.8.16
            elixir: 1.10.3
          - otp: 23.0.2
            elixir: 1.10.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: '${{matrix.otp}}'
          elixir-version: '${{matrix.elixir}}'
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
      - name: Prerelease
        run: test/prerelease.sh

  warnings_as_errors:
    name: Compile without warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: 23.0.2
          elixir-version: 1.10.3
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix compile --warnings-as-errors

  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: 23.0.2
          elixir-version: 1.10.3
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix docs
      - run: test -f doc/index.html && echo "doc/index.html exists."
      - run: test -f doc/ex_doc.epub && echo "doc/ex_doc.epub exists."

  check_formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: 23.0.2
          elixir-version: 1.10.3
      - run: mix format --check-formatted

  check_js:
    name: npm test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Node.js 10.x
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 10.10.0
      - run: npm install --prefix assets
      - run: npm run --prefix assets lint
      - run: apt -y install xorg xvfb gtk2-engines-pixbuf install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
      - run: npm run --prefix assets test
        env:
          CI: true
